# title: jekyll-rtd-theme
# description: Just another documentation theme compatible with GitHub Pages

# theme: null

lang: "ja"
title: Matomeプラス
description: twitterでのつぶやきを中心に色んな問題のまとめです
url: "https://okmksato.github.io/"
theme: null
twitter:
  card: summary_large_image

previous: 前ページ
next: 次ページ
search_docs: 'サイト内検索...'

search_results: '検索結果'
search_results_found: '# ページ見つかりました'
search_results_not_found: '一致するページは見つかりませんでした'

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
